"use client";

import { useCallback, useSyncExternalStore } from "react";

export type Language = "en" | "zh-CN";

const translations = {
  en: {
    settings: "Settings",
    settingsSections: "Settings sections",
    closeSettings: "Close settings",
    display: "Display",
    models: "Models",
    skills: "Skills",
    plugins: "Plugins",
    theme: "Theme",
    language: "Language",
    light: "Light",
    dark: "Dark",
    english: "English",
    chinese: "简体中文",
    themeDescription: "Choose the appearance of Pi Web.",
    languageDescription: "Choose the display language for the interface.",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
    showSidebar: "Show sidebar",
    hideSidebar: "Hide sidebar",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close: "Close",
    loadingSession: "Loading session...",
    scrollToLoadEarlierMessages: "Scroll up to load earlier messages ({count} hidden)",
    runningTool: "Running tool...",
    runningTools: "Running {tools}...",
    waitingForModel: "Waiting for model...",
    runningCommand: "Running command...",
    thinking: "Thinking...",
    extensionRequest: "extension request",
    extensionPanel: "Extension panel",
    cancel: "Cancel",
    confirm: "Confirm",
    submit: "Submit",
    queued: "Queued",
    steer: "Steer",
    followUp: "Follow-up",
    recallToInput: "Recall to input",
    recallQueuedMessages: "Remove all queued messages and put them back into the input box for editing",
    retrying: "Retrying",
    compacted: "Compacted",
    tokens: "tokens",
    saved: "saved",
    removeImage: "Remove image",
    loadingCommands: "Loading commands...",
    slashCommands: "Slash commands",
    tabOrEnter: "Tab / Enter",
    noSlashCommands: "No extension, prompt, or skill commands found",
    builtIn: "Built-in",
    extensions: "Extensions",
    prompts: "Prompts",
    commandSkills: "Skills",
    match: "match",
    matches: "matches",
    command: "command",
    commands: "commands",
    loadingFiles: "Loading files...",
    files: "Files",
    searchingAllFiles: "searching all files...",
    indexTruncated: "index truncated",
    searching: "Searching...",
    noMatchingFiles: "No matching files",
    steerOrQueueFollowUp: "Steer now / queue follow-up...",
    agentRunning: "Agent is running...",
    messageWithCommands: "Message... Type / for commands, @ for files",
    imageAttachmentsCannotQueue: "Image attachments cannot be queued while the agent is running",
    injectMessageNow: "Interrupt the current run and inject this message now",
    queueMessageAfterFinish: "Queue this message after the agent finishes",
    attachImage: "Attach image",
    disableCompletionSound: "Disable completion sound",
    enableCompletionSound: "Enable completion sound",
    changeReasoningLevel: "Change reasoning level: {level}",
    reasoningLevel: "Change reasoning level",
    moreControls: "More controls",
    more: "More",
    stopCompaction: "Stop compaction",
    compactContext: "Compact context",
    compacting: "Compacting...",
    compact: "Compact",
    changeToolPreset: "Change tool preset: {preset}",
    toolPreset: "Change tool preset",
    sendMessage: "Send message",
    stopAgent: "Stop agent",
    stop: "Stop",
    collapseControls: "Collapse controls",
    usePiDefault: "Use pi default",
    reasoningOff: "Reasoning off",
    minimalReasoning: "Minimal reasoning",
    lowReasoning: "Low reasoning",
    mediumReasoning: "Medium reasoning",
    highReasoning: "High reasoning",
    extraHighReasoning: "Extra-high reasoning",
    maxReasoning: "Max reasoning",
    noToolsReadOnly: "No tools, read-only",
    fourBuiltInTools: "4 built-in tools",
    allBuiltInTools: "All built-in tools",
    compactCommandDescription: "Compress context, optionally with instructions",
    reloadCommandDescription: "Reload extensions, skills, prompts, and tools",
    nameCommandDescription: "Set the session display name",
    sessionCommandDescription: "Show session message, token, and cost stats",
    copyCommandDescription: "Copy the last assistant message",
    selectProject: "Select project",
    selectProjectFirst: "Select a project first",
    noMatchingProjects: "No matching projects",
    noProjectsYet: "No projects yet",
    useDefaultDirectory: "Use default directory",
    customPath: "Custom path…",
    projectPathPlaceholder: "/path/to/project",
    filterProjects: "Filter projects…",
    checking: "Checking…",
    open: "Open",
    switchWorktree: "Switch worktree",
    switchWorktreeWithPath: "Switch worktree: {path}",
    openRepoRoot: "Open repo root",
    openRepoRootDescription: "Open the repository root to manage worktrees.",
    gitRepoRootOnly: "Git repo root only",
    gitRepoRootOnlyDescription: "Worktrees are available in Git repository roots.",
    checkingWorktrees: "Checking worktrees for this directory.",
    worktreesLoading: "Worktrees...",
    createWorktree: "Create a worktree checkout for a branch",
    newWorktree: "New worktree…",
    branchName: "branch name",
    creating: "Creating…",
    create: "Create",
    main: "main",
    removeWorktree: "Remove worktree checkout {path}; the branch is kept",
    uncommittedChanges: "Uncommitted changes. Force remove checkout?",
    force: "Force",
    newSession: "New",
    newSessionIn: "New session in {cwd}",
    refresh: "Refresh",
    loading: "Loading...",
    noSessionsFound: "No sessions found",
    explorer: "Explorer",
    uploadFiles: "Upload files",
    uploadFilesToProjectRoot: "Upload files to project root",
    refreshExplorer: "Refresh explorer",
    agentRunningLabel: "Agent running",
    newActivity: "New activity",
    newSessionActivity: "New session activity",
    deleteSession: "Delete {title}?",
    delete: "Delete",
    rename: "Rename",
    expandForks: "Expand forks",
    collapseForks: "Collapse forks",
    messagesCount: "{count} msgs",
    worktree: "Worktree: {cwd}",
    justNow: "just now",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    daysAgo: "{count}d ago",
    closeTab: "Close",
    closeTabWithLabel: "Close {label}",
  },
  "zh-CN": {
    settings: "设置",
    settingsSections: "设置分类",
    closeSettings: "关闭设置",
    display: "显示",
    models: "模型",
    skills: "技能",
    plugins: "插件",
    theme: "主题",
    language: "语言",
    light: "浅色",
    dark: "深色",
    english: "English",
    chinese: "简体中文",
    themeDescription: "选择 Pi Web 的外观。",
    languageDescription: "选择界面的显示语言。",
    switchToLight: "切换至浅色模式",
    switchToDark: "切换至深色模式",
    showSidebar: "显示侧边栏",
    hideSidebar: "隐藏侧边栏",
    minimize: "最小化",
    maximize: "最大化",
    restore: "还原",
    close: "关闭",
    loadingSession: "正在加载会话...",
    scrollToLoadEarlierMessages: "向上滚动以加载更早的消息（隐藏了 {count} 条）",
    runningTool: "正在运行工具...",
    runningTools: "正在运行 {tools}...",
    waitingForModel: "正在等待模型...",
    runningCommand: "正在运行命令...",
    thinking: "思考中...",
    extensionRequest: "扩展请求",
    extensionPanel: "扩展面板",
    cancel: "取消",
    confirm: "确认",
    submit: "提交",
    queued: "已排队",
    steer: "引导",
    followUp: "后续消息",
    recallToInput: "恢复到输入框",
    recallQueuedMessages: "移除所有排队消息，并将其放回输入框以便编辑",
    retrying: "正在重试",
    compacted: "已压缩",
    tokens: "令牌",
    saved: "已节省",
    removeImage: "移除图片",
    loadingCommands: "正在加载命令...",
    slashCommands: "斜杠命令",
    tabOrEnter: "Tab / Enter",
    noSlashCommands: "未找到扩展、提示词或技能命令",
    builtIn: "内置",
    extensions: "扩展",
    prompts: "提示词",
    commandSkills: "技能",
    match: "个匹配项",
    matches: "个匹配项",
    command: "个命令",
    commands: "个命令",
    loadingFiles: "正在加载文件...",
    files: "文件",
    searchingAllFiles: "正在搜索所有文件...",
    indexTruncated: "索引已截断",
    searching: "正在搜索...",
    noMatchingFiles: "没有匹配的文件",
    steerOrQueueFollowUp: "立即引导 / 排队后续消息...",
    agentRunning: "Agent 正在运行...",
    messageWithCommands: "输入消息... 输入 / 查看命令，@ 查看文件",
    imageAttachmentsCannotQueue: "Agent 运行时无法将图片附件加入队列",
    injectMessageNow: "中断当前运行并立即注入此消息",
    queueMessageAfterFinish: "在 Agent 完成后将此消息加入队列",
    attachImage: "添加图片",
    disableCompletionSound: "关闭完成提示音",
    enableCompletionSound: "开启完成提示音",
    changeReasoningLevel: "更改推理级别：{level}",
    reasoningLevel: "更改推理级别",
    moreControls: "更多控件",
    more: "更多",
    stopCompaction: "停止压缩",
    compactContext: "压缩上下文",
    compacting: "正在压缩...",
    compact: "压缩",
    changeToolPreset: "更改工具预设：{preset}",
    toolPreset: "更改工具预设",
    sendMessage: "发送消息",
    stopAgent: "停止 Agent",
    stop: "停止",
    collapseControls: "收起控件",
    usePiDefault: "使用 pi 默认设置",
    reasoningOff: "关闭推理",
    minimalReasoning: "最小推理",
    lowReasoning: "低推理",
    mediumReasoning: "中等推理",
    highReasoning: "高推理",
    extraHighReasoning: "超高推理",
    maxReasoning: "最高推理",
    noToolsReadOnly: "不使用工具，只读",
    fourBuiltInTools: "4 个内置工具",
    allBuiltInTools: "所有内置工具",
    compactCommandDescription: "压缩上下文，可选择附加指令",
    reloadCommandDescription: "重新加载扩展、技能、提示词和工具",
    nameCommandDescription: "设置会话显示名称",
    sessionCommandDescription: "显示会话消息、令牌和费用统计",
    copyCommandDescription: "复制最后一条助手消息",
    selectProject: "选择项目",
    selectProjectFirst: "请先选择项目",
    noMatchingProjects: "没有匹配的项目",
    noProjectsYet: "尚无项目",
    useDefaultDirectory: "使用默认目录",
    customPath: "自定义路径…",
    projectPathPlaceholder: "/path/to/project",
    filterProjects: "筛选项目…",
    checking: "正在检查…",
    open: "打开",
    switchWorktree: "切换工作树",
    switchWorktreeWithPath: "切换工作树：{path}",
    openRepoRoot: "打开仓库根目录",
    openRepoRootDescription: "打开仓库根目录以管理工作树。",
    gitRepoRootOnly: "仅 Git 仓库根目录",
    gitRepoRootOnlyDescription: "工作树仅在 Git 仓库根目录可用。",
    checkingWorktrees: "正在检查此目录的工作树。",
    worktreesLoading: "工作树…",
    createWorktree: "为分支创建工作树检出",
    newWorktree: "新建工作树…",
    branchName: "分支名称",
    creating: "正在创建…",
    create: "创建",
    main: "主工作树",
    removeWorktree: "移除工作树检出 {path}；分支将保留",
    uncommittedChanges: "存在未提交的更改。要强制移除检出吗？",
    force: "强制移除",
    newSession: "新建",
    newSessionIn: "在 {cwd} 中新建会话",
    refresh: "刷新",
    loading: "正在加载…",
    noSessionsFound: "未找到会话",
    explorer: "资源管理器",
    uploadFiles: "上传文件",
    uploadFilesToProjectRoot: "上传文件到项目根目录",
    refreshExplorer: "刷新资源管理器",
    agentRunningLabel: "Agent 正在运行",
    newActivity: "有新动态",
    newSessionActivity: "会话有新动态",
    deleteSession: "删除“{title}”？",
    delete: "删除",
    rename: "重命名",
    expandForks: "展开分支",
    collapseForks: "折叠分支",
    messagesCount: "{count} 条消息",
    worktree: "工作树：{cwd}",
    justNow: "刚刚",
    minutesAgo: "{count} 分钟前",
    hoursAgo: "{count} 小时前",
    daysAgo: "{count} 天前",
    closeTab: "关闭",
    closeTabWithLabel: "关闭 {label}",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

const listeners = new Set<() => void>();

function normalizeLanguage(value: string | undefined): Language {
  return value === "zh-CN" ? "zh-CN" : "en";
}

function subscribe(callback: () => void): () => void {
  listeners.add(callback);
  return () => listeners.delete(callback);
}

function getSnapshot(): Language {
  if (typeof document === "undefined") return "en";
  return normalizeLanguage(document.documentElement.dataset.language);
}

function getServerSnapshot(): Language {
  return "en";
}

function applyLanguage(language: Language) {
  document.documentElement.dataset.language = language;
  document.documentElement.lang = language;
  try {
    localStorage.setItem("pi-language", language);
  } catch {
    // Ignore storage errors (private mode, quota, etc.).
  }
  listeners.forEach((callback) => callback());
}

export function useLanguage() {
  const language = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);

  const setLanguage = useCallback((next: Language) => {
    applyLanguage(next);
  }, []);

  const t = useCallback((key: TranslationKey) => translations[language][key], [language]);

  return { language, setLanguage, t };
}
