"use client";

import { useCallback, useSyncExternalStore } from "react";

export type Language = "en" | "zh-CN";

const translations = {
  en: {
    settings: "Settings",
    settingsSections: "Settings sections",
    closeSettings: "Close settings",
    display: "Display",
    models: "Models",
    skills: "Skills",
    plugins: "Plugins",
    theme: "Theme",
    themes: "Themes",
    language: "Language",
    light: "Light",
    dark: "Dark",
    english: "English",
    chinese: "简体中文",
    themeDescription: "Choose the appearance of Pi Web.",
    languageDescription: "Choose the display language for the interface.",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
    showSidebar: "Show sidebar",
    hideSidebar: "Hide sidebar",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close: "Close",
    viewFullHistory: "View full history",
    fullHistoryAvailableAfterSave: "Full history is available after the session is saved",
    systemPrompt: "System prompt",
    sessionInfo: "Session info",
    hideFilePanel: "Hide file panel",
    showFilePanel: "Show file panel",
    sessionInfoTitle: "Session Info",
    sessionInfoFile: "File",
    sessionInfoId: "ID",
    sessionInfoInMemory: "In-memory",
    sessionInfoMessages: "Messages",
    sessionInfoTokens: "Tokens",
    sessionInfoUser: "User",
    sessionInfoAssistant: "Assistant",
    sessionInfoToolCalls: "Tool Calls",
    sessionInfoToolResults: "Tool Results",
    sessionInfoTotal: "Total",
    sessionInfoInput: "Input",
    sessionInfoOutput: "Output",
    sessionInfoCacheRead: "Cache Read",
    sessionInfoCacheWrite: "Cache Write",
    sessionInfoCost: "Cost",
    sessionInfoContext: "Context",
    copyFilePath: "Copy file path",
    copySessionId: "Copy session ID",
    sendMessageForSessionInfo: "Send a message or run /session to load session info",
    selectSessionFromSidebar: "Select a session from the sidebar",
    getStarted: "Get Started",
    selectProjectDirectory: "Select a project directory from the sidebar",
    addModelsFromBottom: "Add models via the Models button at the bottom",
    loadingSession: "Loading session...",
    scrollToLoadEarlierMessages: "Scroll up to load earlier messages ({count} hidden)",
    runningTool: "Running tool...",
    runningTools: "Running {tools}...",
    waitingForModel: "Waiting for model...",
    runningCommand: "Running command...",
    thinking: "Thinking...",
    extensionRequest: "extension request",
    extensionPanel: "Extension panel",
    cancel: "Cancel",
    confirm: "Confirm",
    submit: "Submit",
    queued: "Queued",
    steer: "Steer",
    followUp: "Follow-up",
    recallToInput: "Recall to input",
    recallQueuedMessages: "Remove all queued messages and put them back into the input box for editing",
    retrying: "Retrying",
    compacted: "Compacted",
    tokens: "tokens",
    saved: "saved",
    removeImage: "Remove image",
    loadingCommands: "Loading commands...",
    slashCommands: "Slash commands",
    tabOrEnter: "Tab / Enter",
    noSlashCommands: "No extension, prompt, or skill commands found",
    builtIn: "Built-in",
    extensions: "Extensions",
    prompts: "Prompts",
    commandSkills: "Skills",
    match: "match",
    matches: "matches",
    command: "command",
    commands: "commands",
    loadingFiles: "Loading files...",
    files: "Files",
    searchingAllFiles: "searching all files...",
    indexTruncated: "index truncated",
    searching: "Searching...",
    search: "Search",
    noMatchingFiles: "No matching files",
    steerOrQueueFollowUp: "Steer now / queue follow-up...",
    agentRunning: "Agent is running...",
    messageWithCommands: "Message... Type / for commands, @ for files",
    imageAttachmentsCannotQueue: "Image attachments cannot be queued while the agent is running",
    injectMessageNow: "Interrupt the current run and inject this message now",
    queueMessageAfterFinish: "Queue this message after the agent finishes",
    attachImage: "Attach image",
    disableCompletionSound: "Disable completion sound",
    enableCompletionSound: "Enable completion sound",
    soundLabelOn: "Sound: On",
    soundLabelOff: "Sound: Off",
    changeReasoningLevel: "Change reasoning level: {level}",
    reasoningLevel: "Change reasoning level",
    moreControls: "More controls",
    more: "More",
    stopCompaction: "Stop compaction",
    compactContext: "Compact context",
    compacting: "Compacting...",
    compact: "Compact",
    changeToolPreset: "Change tool preset: {preset}",
    toolPreset: "Change tool preset",
    sendMessage: "Send message",
    stopAgent: "Stop agent",
    stop: "Stop",
    collapseControls: "Collapse controls",
    usePiDefault: "Use pi default",
    reasoningOff: "Reasoning off",
    minimalReasoning: "Minimal reasoning",
    lowReasoning: "Low reasoning",
    mediumReasoning: "Medium reasoning",
    highReasoning: "High reasoning",
    extraHighReasoning: "Extra-high reasoning",
    maxReasoning: "Max reasoning",
    noToolsReadOnly: "No tools, read-only",
    fourBuiltInTools: "4 built-in tools",
    allBuiltInTools: "All built-in tools",
    toolOff: "off",
    toolDefault: "default",
    toolFull: "full",
    thinkingAuto: "auto",
    thinkingOff: "off",
    thinkingMinimal: "minimal",
    thinkingLow: "low",
    thinkingMedium: "medium",
    thinkingHigh: "high",
    thinkingExtraHigh: "xhigh",
    thinkingMax: "max",
    compactCommandDescription: "Compress context, optionally with instructions",
    reloadCommandDescription: "Reload extensions, skills, prompts, and tools",
    nameCommandDescription: "Set the session display name",
    sessionCommandDescription: "Show session message, token, and cost stats",
    copyCommandDescription: "Copy the last assistant message",
    selectProject: "Select project",
    selectProjectFirst: "Select a project first",
    noMatchingProjects: "No matching projects",
    noProjectsYet: "No projects yet",
    useDefaultDirectory: "Use default directory",
    customPath: "Custom path…",
    projectPathPlaceholder: "/path/to/project",
    filterProjects: "Filter projects…",
    checking: "Checking…",
    open: "Open",
    switchWorktree: "Switch worktree",
    switchWorktreeWithPath: "Switch worktree: {path}",
    openRepoRoot: "Open repo root",
    openRepoRootDescription: "Open the repository root to manage worktrees.",
    gitRepoRootOnly: "Git repo root only",
    gitRepoRootOnlyDescription: "Worktrees are available in Git repository roots.",
    checkingWorktrees: "Checking worktrees for this directory.",
    worktreesLoading: "Worktrees...",
    createWorktree: "Create a worktree checkout for a branch",
    newWorktree: "New worktree…",
    branchName: "branch name",
    creating: "Creating…",
    create: "Create",
    main: "main",
    removeWorktree: "Remove worktree checkout {path}; the branch is kept",
    uncommittedChanges: "Uncommitted changes. Force remove checkout?",
    force: "Force",
    sessions: "Sessions",
    newSession: "New",
    newSessionIn: "New session in {cwd}",
    refresh: "Refresh",
    loading: "Loading...",
    noSessionsFound: "No sessions found",
    explorer: "Explorer",
    uploadFiles: "Upload files",
    uploadFilesToProjectRoot: "Upload files to project root",
    refreshExplorer: "Refresh explorer",
    agentRunningLabel: "Agent running",
    newActivity: "New activity",
    newSessionActivity: "New session activity",
    deleteSession: "Delete {title}?",
    delete: "Delete",
    rename: "Rename",
    expandForks: "Expand forks",
    collapseForks: "Collapse forks",
    messagesCount: "{count} msgs",
    worktree: "Worktree: {cwd}",
    justNow: "just now",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    daysAgo: "{count}d ago",
    closeTab: "Close",
    closeTabWithLabel: "Close {label}",
    modelsHideApiKey: "Hide API key",
    modelsShowApiKey: "Show API key",
    modelsInheritNone: "— inherit / none —",
    modelsProvider: "Provider",
    modelsProviderName: "Provider name",
    modelsBaseUrl: "Base URL",
    modelsApiKey: "API Key",
    modelsApiKeyHelp: "Prefix with ! to run a shell command, or use an env var name",
    modelsApiKeyPlaceholder: "ENV_VAR_NAME, !shell-command, or literal key",
    modelsApi: "API",
    modelsDefault: "Default",
    modelsDisabled: "Disabled",
    modelsCustom: "Custom",
    modelsModelSection: "Model",
    modelsTestingConnection: "Testing model connection...",
    modelsConnected: "Connected",
    modelsFailed: "Failed",
    modelsTestConnection: "Test model connection",
    modelsTesting: "Testing…",
    modelsTest: "Test",
    modelsOk: "OK",
    modelsRemove: "Remove",
    modelsIdRequired: "ID *",
    modelsName: "Name",
    modelsDisplayName: "Display name",
    modelsApiOverride: "API override",
    modelsReasoningThinking: "Reasoning / thinking",
    modelsImageInput: "Image input",
    modelsDeepSeekCompat: "DeepSeek thinking compat",
    modelsThinkingLevelMap: "Thinking level map",
    modelsClearAll: "clear all",
    modelsContextWindow: "Context window (tokens)",
    modelsMaxOutputTokens: "Max output tokens",
    modelsCostPerMillionTokens: "Cost (per million tokens)",
    modelsSubscription: "Subscription",
    modelsNotConnected: "not connected",
    modelsAlreadyConnected: "Already connected. You can re-login or disconnect.",
    modelsConnectAccount: "Connect your {provider} account.",
    modelsOpeningBrowser: "Opening browser…",
    modelsCompleteSignIn: "Complete sign-in in the browser, then copy the redirect URL from the address bar and paste it below.",
    modelsBrowserDidNotOpen: "If the browser window did not open,",
    modelsOpenLoginPage: "click here to open the login page",
    modelsEnterValue: "Enter value…",
    modelsOpenVerificationPage: "Open the verification page and enter this code:",
    modelsExpiresInMinutes: "Expires in {count} minutes.",
    modelsConnectedSuccessfully: "Connected successfully.",
    modelsReLogin: "Re-login",
    modelsLogin: "Login",
    modelsDisconnect: "Disconnect",
    modelsConnectionLost: "Connection lost",
    modelsVerifying: "Verifying…",
    modelsContinuing: "Continuing…",
    modelsServerError: "Server error {status}",
    modelsNetworkError: "Network error",
    modelsConfigured: "configured",
    modelsNotConfigured: "not configured",
    modelsApiKeyStored: "API key is stored. Enter a new key below to replace it, or disconnect to remove it.",
    modelsEnableModels: "Enter your {provider} API key to enable {count} {models}.",
    modelsSingular: "model",
    modelsPlural: "models",
    modelsEnterNewKey: "Enter new key to replace…",
    modelsSaving: "Saving…",
    modelsSaved: "Saved",
    modelsRemoving: "Removing…",
    modelsSearchProviders: "Search providers…",
    modelsNoProvidersMatch: "No providers match",
    modelsCompatibleProvider: "OpenAI / Anthropic compatible",
    modelsCustomEndpointFormat: "Custom endpoint format",
    modelsSubscriptions: "Subscriptions",
    modelsCount: "{count} models",
    modelsLoading: "Loading…",
    modelsNewModel: "new model",
    modelsAddModel: "+ model",
    modelsAddProvider: "+ Add provider",
    modelsSelectProviderOrModel: "Select a provider or model",
    modelsClose: "Close models",
    modelsSave: "Save",
    global: "global",
    project: "project",
    path: "path",
    addPlugin: "Add plugin",
    addPluginTitle: "Add Plugin",
    pluginSource: "Source",
    install: "Install",
    installing: "Installing...",
    examples: "Examples",
    disabled: "Disabled",
    filtered: "filtered",
    noResources: "No resources",
    packageDisabled: "Package disabled",
    noResolvedResources: "No resolved resources",
    unknown: "Unknown",
    installedVersion: "installed {version}",
    configuredVersion: "configured {version}",
    enablePackage: "Enable package",
    disablePackage: "Disable package",
    update: "Update",
    updating: "Updating...",
    reloadSession: "Reload session",
    reloading: "Reloading...",
    reloadCurrentSession: "Reload current session",
    openSessionToReload: "Open a session to reload",
    remove: "Remove",
    removing: "Removing...",
    status: "Status",
    version: "Version",
    package: "Package",
    resources: "Resources",
    installedPath: "Installed path",
    notFound: "Not found",
    cwd: "Cwd",
    resolvedResources: "Resolved Resources",
    packageRemoved: "Package removed.",
    packageInstalled: "Package installed.",
    packageUpdated: "Package updated.",
    packageDisabledMessage: "Package disabled.",
    packageEnabled: "Package enabled.",
    sessionReloaded: "Session reloaded.",
    noPluginsConfigured: "No plugins configured",
    selectPackage: "Select a package",
    diagnosticsCount: "{count} diagnostic{suffix}",
    pluginResourceTotals: "{extensions} ext · {skills} skills · {prompts} prompts · {themes} themes",
    extensionsCount: "{count} ext",
    skillsCount: "{count} skills",
    promptsCount: "{count} prompts",
    themesCount: "{count} themes",
    addSkill: "Add skill",
    addSkillTitle: "Add Skill",
    skillSearchPlaceholder: "e.g. react, testing, deploy",
    noSkillsFound: "No skills found",
    skillSearchHint: "Search skills.sh to discover and install skills for your agent.",
    visibleInModelPrompt: "Visible in model prompt — click to disable",
    hiddenFromModelPrompt: "Hidden from model prompt — click to enable",
    check: "Check",
    upToDate: "Up to date",
    automaticChecksUnavailable: "Automatic checks unavailable",
    checkFailed: "Check failed",
    name: "Name",
    description: "Description",
    selectSkill: "Select a skill",
    checkUpdates: "Check updates",
    updateAvailable: "Update available",
    installed: "Installed",
    updatesCount: "{count} update{suffix}",
    downloadFile: "Download file",
    loadingFile: "Loading...",
    noChanges: "No changes",
    unchangedLines: "... {count} unchanged lines ...",
    lines: "{count} lines",
    liveSyncActive: "Live sync active",
    notWatching: "Not watching",
    live: "live",
    static: "static",
    source: "Source",
    diff: "Diff",
    enableWordWrap: "Enable word wrap",
    disableWordWrap: "Disable word wrap",
    wrap: "wrap",
    code: "Code",
    preview: "Preview",
    raw: "Raw",
    htmlPreview: "HTML preview",
    image: "image",
    audio: "audio",
    docxPreview: "docx preview",
    failedToLoadImage: "Failed to load image",
    failedToLoadAudio: "Failed to load audio",
    docxTooLargeForPreview: "DOCX too large for preview (>10MB)",
    previewFile: "Preview {file}",
    branches: "Branches",
    noActiveSession: "No active session",
    sessionHasNoBranches: "This session has no branches",
    copyMessage: "Copy message",
    editFromHere: "Edit from here — branches within this session",
    creatingNewSession: "Creating new session…",
    newSessionFromHere: "New session — creates an independent copy from here",
    estimatedStreamingTokenCount: "Estimated token count while streaming",
    tokensPerSecond: "{count} t/s",
    thinkingContentUnavailable: "Thinking content unavailable",
    loadingThinking: "Loading thinking...",

    conversationCompacted: "Conversation compacted",
    compactionSummaryDescription: "The conversation history before this point was compacted into the following summary:",
    noSummary: "(no summary)",
    fileContext: "File context: {context}",
    readFilesCount: "{count} read",
    modifiedFilesCount: "{count} modified",
    modifiedFiles: "Modified files",
    readFiles: "Read files",
    hiddenExtensionMessage: "hidden extension message",
    noMessage: "(no message)",
    showExtensionMessage: "Show extension message",
    copied: "Copied",
    copy: "Copy",
    collapse: "Collapse",
    expand: "Expand",
    hideDetails: "Hide details",
    showDetails: "Show details",
    before: "Before",
    after: "After",
    noOutput: "(no output)",
    extension: "extension",
    assistant: "assistant",
    favorites: "Favorites",
    favorite: "Favorite",
    unfavorite: "Unfavorite",

    processStepThinking: "Thinking",
    processStepFileRead: "Read",
    processStepFileCreate: "Create",
    processStepFileEdit: "Edit",
    processStepFileDelete: "Delete",
    processStepSearch: "Search",
    processStepFind: "Find",
    processStepList: "List",
    processStepRead: "Read",
    processStepFetch: "Fetch",
    processStepDelete: "Delete",
    processStepCopy: "Copy",
    processStepCommand: "Run",
    processStepTool: "Tool",
    processStepTodo: "Todo",
    processStepArtifact: "Artifact",
    processStepCompaction: "Compaction",
    processStepError: "Error",
    processWorking: "Working...",
    processUsed: "Used {summary}",
    processToolCount: "{count} tool",
    processToolsCount: "{count} tools",
    processFailedCount: " ({failed} failed)",
    processThoughtCount: "{count} thought",
    processThoughtsCount: "{count} thoughts",
    processThoughtDone: "Thought {duration}s",
    processThoughtDoneNoDuration: "Thought",
    processCustomCount: "{count} event",
    processCustomsCount: "{count} events",
    processCompleted: "Process complete",
    processOutput: "Process output",
    processTabMode: "Tab mode",
    processTimelineMode: "Timeline mode",
    processFailedStep: "failed",
  },
  "zh-CN": {
    settings: "设置",
    settingsSections: "设置分类",
    closeSettings: "关闭设置",
    display: "显示",
    models: "模型",
    skills: "技能",
    plugins: "插件",
    theme: "主题",
    themes: "主题",
    language: "语言",
    light: "浅色",
    dark: "深色",
    english: "English",
    chinese: "简体中文",
    themeDescription: "选择 Pi Web 的外观。",
    languageDescription: "选择界面的显示语言。",
    switchToLight: "切换至浅色模式",
    switchToDark: "切换至深色模式",
    showSidebar: "显示侧边栏",
    hideSidebar: "隐藏侧边栏",
    minimize: "最小化",
    maximize: "最大化",
    restore: "还原",
    close: "关闭",
    viewFullHistory: "查看完整历史",
    fullHistoryAvailableAfterSave: "保存会话后可查看完整历史",
    systemPrompt: "系统提示词",
    sessionInfo: "会话信息",
    hideFilePanel: "隐藏文件面板",
    showFilePanel: "显示文件面板",
    sessionInfoTitle: "会话信息",
    sessionInfoFile: "文件",
    sessionInfoId: "ID",
    sessionInfoInMemory: "内存中",
    sessionInfoMessages: "消息",
    sessionInfoTokens: "令牌",
    sessionInfoUser: "用户",
    sessionInfoAssistant: "助手",
    sessionInfoToolCalls: "工具调用",
    sessionInfoToolResults: "工具结果",
    sessionInfoTotal: "总计",
    sessionInfoInput: "输入",
    sessionInfoOutput: "输出",
    sessionInfoCacheRead: "缓存读取",
    sessionInfoCacheWrite: "缓存写入",
    sessionInfoCost: "费用",
    sessionInfoContext: "上下文",
    copyFilePath: "复制文件路径",
    copySessionId: "复制会话 ID",
    sendMessageForSessionInfo: "发送消息或运行 /session 以加载会话信息",
    selectSessionFromSidebar: "请从侧边栏选择会话",
    getStarted: "开始使用",
    selectProjectDirectory: "从侧边栏选择项目目录",
    addModelsFromBottom: "通过底部的“模型”按钮添加模型",
    loadingSession: "正在加载会话...",
    scrollToLoadEarlierMessages: "向上滚动以加载更早的消息（隐藏了 {count} 条）",
    runningTool: "正在运行工具...",
    runningTools: "正在运行 {tools}...",
    waitingForModel: "正在等待模型...",
    runningCommand: "正在运行命令...",
    thinking: "思考中...",
    extensionRequest: "扩展请求",
    extensionPanel: "扩展面板",
    cancel: "取消",
    confirm: "确认",
    submit: "提交",
    queued: "已排队",
    steer: "引导",
    followUp: "后续消息",
    recallToInput: "恢复到输入框",
    recallQueuedMessages: "移除所有排队消息，并将其放回输入框以便编辑",
    retrying: "正在重试",
    compacted: "已压缩",
    tokens: "令牌",
    saved: "已节省",
    removeImage: "移除图片",
    loadingCommands: "正在加载命令...",
    slashCommands: "斜杠命令",
    tabOrEnter: "Tab / Enter",
    noSlashCommands: "未找到扩展、提示词或技能命令",
    builtIn: "内置",
    extensions: "扩展",
    prompts: "提示词",
    commandSkills: "技能",
    match: "个匹配项",
    matches: "个匹配项",
    command: "个命令",
    commands: "个命令",
    loadingFiles: "正在加载文件...",
    files: "文件",
    searchingAllFiles: "正在搜索所有文件...",
    indexTruncated: "索引已截断",
    searching: "正在搜索...",
    search: "搜索",
    noMatchingFiles: "没有匹配的文件",
    steerOrQueueFollowUp: "立即引导 / 排队后续消息...",
    agentRunning: "Agent 正在运行...",
    messageWithCommands: "输入消息... 输入 / 查看命令，@ 查看文件",
    imageAttachmentsCannotQueue: "Agent 运行时无法将图片附件加入队列",
    injectMessageNow: "中断当前运行并立即注入此消息",
    queueMessageAfterFinish: "在 Agent 完成后将此消息加入队列",
    attachImage: "添加图片",
    disableCompletionSound: "关闭完成提示音",
    enableCompletionSound: "开启完成提示音",
    soundLabelOn: "提示音：开启",
    soundLabelOff: "提示音：关闭",
    changeReasoningLevel: "更改推理级别：{level}",
    reasoningLevel: "更改推理级别",
    moreControls: "更多控件",
    more: "更多",
    stopCompaction: "停止压缩",
    compactContext: "压缩上下文",
    compacting: "正在压缩...",
    compact: "压缩",
    changeToolPreset: "更改工具预设：{preset}",
    toolPreset: "更改工具预设",
    sendMessage: "发送消息",
    stopAgent: "停止 Agent",
    stop: "停止",
    collapseControls: "收起控件",
    usePiDefault: "使用 pi 默认设置",
    reasoningOff: "关闭推理",
    minimalReasoning: "最小推理",
    lowReasoning: "低推理",
    mediumReasoning: "中等推理",
    highReasoning: "高推理",
    extraHighReasoning: "超高推理",
    maxReasoning: "最高推理",
    noToolsReadOnly: "不使用工具，只读",
    fourBuiltInTools: "4 个内置工具",
    allBuiltInTools: "所有内置工具",
    toolOff: "关闭",
    toolDefault: "默认",
    toolFull: "完整",
    thinkingAuto: "自动",
    thinkingOff: "关闭",
    thinkingMinimal: "最小",
    thinkingLow: "低",
    thinkingMedium: "中等",
    thinkingHigh: "高",
    thinkingExtraHigh: "超高",
    thinkingMax: "最高",
    compactCommandDescription: "压缩上下文，可选择附加指令",
    reloadCommandDescription: "重新加载扩展、技能、提示词和工具",
    nameCommandDescription: "设置会话显示名称",
    sessionCommandDescription: "显示会话消息、令牌和费用统计",
    copyCommandDescription: "复制最后一条助手消息",
    selectProject: "选择项目",
    selectProjectFirst: "请先选择项目",
    noMatchingProjects: "没有匹配的项目",
    noProjectsYet: "尚无项目",
    useDefaultDirectory: "使用默认目录",
    customPath: "自定义路径…",
    projectPathPlaceholder: "/path/to/project",
    filterProjects: "筛选项目…",
    checking: "正在检查…",
    open: "打开",
    switchWorktree: "切换工作树",
    switchWorktreeWithPath: "切换工作树：{path}",
    openRepoRoot: "打开仓库根目录",
    openRepoRootDescription: "打开仓库根目录以管理工作树。",
    gitRepoRootOnly: "仅 Git 仓库根目录",
    gitRepoRootOnlyDescription: "工作树仅在 Git 仓库根目录可用。",
    checkingWorktrees: "正在检查此目录的工作树。",
    worktreesLoading: "工作树…",
    createWorktree: "为分支创建工作树检出",
    newWorktree: "新建工作树…",
    branchName: "分支名称",
    creating: "正在创建…",
    create: "创建",
    main: "主工作树",
    removeWorktree: "移除工作树检出 {path}；分支将保留",
    uncommittedChanges: "存在未提交的更改。要强制移除检出吗？",
    force: "强制移除",
    sessions: "会话",
    newSession: "新建",
    newSessionIn: "在 {cwd} 中新建会话",
    refresh: "刷新",
    loading: "正在加载…",
    noSessionsFound: "未找到会话",
    explorer: "资源管理器",
    uploadFiles: "上传文件",
    uploadFilesToProjectRoot: "上传文件到项目根目录",
    refreshExplorer: "刷新资源管理器",
    agentRunningLabel: "Agent 正在运行",
    newActivity: "有新动态",
    newSessionActivity: "会话有新动态",
    deleteSession: "删除“{title}”？",
    delete: "删除",
    rename: "重命名",
    expandForks: "展开分支",
    collapseForks: "折叠分支",
    messagesCount: "{count} 条消息",
    worktree: "工作树：{cwd}",
    justNow: "刚刚",
    minutesAgo: "{count} 分钟前",
    hoursAgo: "{count} 小时前",
    daysAgo: "{count} 天前",
    closeTab: "关闭",
    closeTabWithLabel: "关闭 {label}",
    modelsHideApiKey: "隐藏 API 密钥",
    modelsShowApiKey: "显示 API 密钥",
    modelsInheritNone: "— 继承 / 无 —",
    modelsProvider: "提供商",
    modelsProviderName: "提供商名称",
    modelsBaseUrl: "基础 URL",
    modelsApiKey: "API 密钥",
    modelsApiKeyHelp: "使用 ! 前缀运行 shell 命令，或使用环境变量名称",
    modelsApiKeyPlaceholder: "环境变量名称、!shell 命令或原始密钥",
    modelsApi: "API",
    modelsDefault: "默认",
    modelsDisabled: "已禁用",
    modelsCustom: "自定义",
    modelsModelSection: "模型",
    modelsTestingConnection: "正在测试模型连接...",
    modelsConnected: "已连接",
    modelsFailed: "失败",
    modelsTestConnection: "测试模型连接",
    modelsTesting: "测试中…",
    modelsTest: "测试",
    modelsOk: "正常",
    modelsRemove: "移除",
    modelsIdRequired: "ID *",
    modelsName: "名称",
    modelsDisplayName: "显示名称",
    modelsApiOverride: "覆盖 API",
    modelsReasoningThinking: "推理 / 思考",
    modelsImageInput: "图片输入",
    modelsDeepSeekCompat: "DeepSeek 思考兼容模式",
    modelsThinkingLevelMap: "思考级别映射",
    modelsClearAll: "清除全部",
    modelsContextWindow: "上下文窗口（令牌）",
    modelsMaxOutputTokens: "最大输出令牌数",
    modelsCostPerMillionTokens: "费用（每百万令牌）",
    modelsSubscription: "订阅",
    modelsNotConnected: "未连接",
    modelsAlreadyConnected: "已连接。你可以重新登录或断开连接。",
    modelsConnectAccount: "连接你的 {provider} 账户。",
    modelsOpeningBrowser: "正在打开浏览器…",
    modelsCompleteSignIn: "请在浏览器中完成登录，然后复制地址栏中的重定向 URL 并粘贴到下方。",
    modelsBrowserDidNotOpen: "如果浏览器窗口未打开，",
    modelsOpenLoginPage: "点击此处打开登录页面",
    modelsEnterValue: "输入值…",
    modelsOpenVerificationPage: "打开验证页面并输入此代码：",
    modelsExpiresInMinutes: "将在 {count} 分钟后过期。",
    modelsConnectedSuccessfully: "连接成功。",
    modelsReLogin: "重新登录",
    modelsLogin: "登录",
    modelsDisconnect: "断开连接",
    modelsConnectionLost: "连接已断开",
    modelsVerifying: "验证中…",
    modelsContinuing: "正在继续…",
    modelsServerError: "服务器错误 {status}",
    modelsNetworkError: "网络错误",
    modelsConfigured: "已配置",
    modelsNotConfigured: "未配置",
    modelsApiKeyStored: "API 密钥已保存。请在下方输入新密钥以替换它，或断开连接以移除它。",
    modelsEnableModels: "输入你的 {provider} API 密钥以启用 {count} 个{models}。",
    modelsSingular: "模型",
    modelsPlural: "模型",
    modelsEnterNewKey: "输入新密钥以替换…",
    modelsSaving: "保存中…",
    modelsSaved: "已保存",
    modelsRemoving: "移除中…",
    modelsSearchProviders: "搜索提供商…",
    modelsNoProvidersMatch: "没有匹配的提供商",
    modelsCompatibleProvider: "兼容 OpenAI / Anthropic",
    modelsCustomEndpointFormat: "自定义端点格式",
    modelsSubscriptions: "订阅",
    modelsCount: "{count} 个模型",
    modelsLoading: "加载中…",
    modelsNewModel: "新模型",
    modelsAddModel: "+ 添加模型",
    modelsAddProvider: "+ 添加提供商",
    modelsSelectProviderOrModel: "选择提供商或模型",
    modelsClose: "关闭模型设置",
    modelsSave: "保存",
    global: "全局",
    project: "项目",
    path: "路径",
    addPlugin: "添加插件",
    addPluginTitle: "添加插件",
    pluginSource: "来源",
    install: "安装",
    installing: "正在安装...",
    examples: "示例",
    disabled: "已禁用",
    filtered: "已筛选",
    noResources: "没有资源",
    packageDisabled: "软件包已禁用",
    noResolvedResources: "没有已解析的资源",
    unknown: "未知",
    installedVersion: "已安装 {version}",
    configuredVersion: "已配置 {version}",
    enablePackage: "启用软件包",
    disablePackage: "禁用软件包",
    update: "更新",
    updating: "正在更新...",
    reloadSession: "重新加载会话",
    reloading: "正在重新加载...",
    reloadCurrentSession: "重新加载当前会话",
    openSessionToReload: "打开一个会话以重新加载",
    remove: "移除",
    removing: "正在移除...",
    status: "状态",
    version: "版本",
    package: "软件包",
    resources: "资源",
    installedPath: "安装路径",
    notFound: "未找到",
    cwd: "当前目录",
    resolvedResources: "已解析资源",
    packageRemoved: "软件包已移除。",
    packageInstalled: "软件包已安装。",
    packageUpdated: "软件包已更新。",
    packageDisabledMessage: "软件包已禁用。",
    packageEnabled: "软件包已启用。",
    sessionReloaded: "会话已重新加载。",
    noPluginsConfigured: "未配置插件",
    selectPackage: "选择一个软件包",
    diagnosticsCount: "{count} 条诊断信息",
    pluginResourceTotals: "{extensions} 个扩展 · {skills} 个技能 · {prompts} 个提示词 · {themes} 个主题",
    extensionsCount: "{count} 个扩展",
    skillsCount: "{count} 个技能",
    promptsCount: "{count} 个提示词",
    themesCount: "{count} 个主题",
    addSkill: "添加技能",
    addSkillTitle: "添加技能",
    skillSearchPlaceholder: "例如：react、testing、deploy",
    noSkillsFound: "未找到技能",
    skillSearchHint: "搜索 skills.sh，发现并为你的 Agent 安装技能。",
    visibleInModelPrompt: "在模型提示词中可见 — 点击以禁用",
    hiddenFromModelPrompt: "在模型提示词中隐藏 — 点击以启用",
    check: "检查",
    upToDate: "已是最新",
    automaticChecksUnavailable: "无法自动检查更新",
    checkFailed: "检查失败",
    name: "名称",
    description: "描述",
    selectSkill: "选择一个技能",
    checkUpdates: "检查更新",
    updateAvailable: "有可用更新",
    installed: "已安装",
    updatesCount: "{count} 个更新",
    downloadFile: "下载文件",
    loadingFile: "正在加载...",
    noChanges: "没有更改",
    unchangedLines: "... {count} 行未更改 ...",
    lines: "{count} 行",
    liveSyncActive: "实时同步已启用",
    notWatching: "未监视",
    live: "实时",
    static: "静态",
    source: "源文件",
    diff: "差异",
    enableWordWrap: "启用自动换行",
    disableWordWrap: "禁用自动换行",
    wrap: "换行",
    code: "代码",
    preview: "预览",
    raw: "原始内容",
    htmlPreview: "HTML 预览",
    image: "图片",
    audio: "音频",
    docxPreview: "DOCX 预览",
    failedToLoadImage: "加载图片失败",
    failedToLoadAudio: "加载音频失败",
    docxTooLargeForPreview: "DOCX 文件过大，无法预览（超过 10MB）",
    previewFile: "预览 {file}",
    branches: "分支",
    noActiveSession: "没有活动会话",
    sessionHasNoBranches: "此会话没有分支",
    copyMessage: "复制消息",
    editFromHere: "从此处编辑 — 在此会话内创建分支",
    creatingNewSession: "正在创建新会话…",
    newSessionFromHere: "新建会话 — 从此处创建独立副本",
    estimatedStreamingTokenCount: "流式输出期间的预估令牌数",
    tokensPerSecond: "{count} 令牌/秒",
    thinkingContentUnavailable: "思考内容不可用",
    loadingThinking: "正在加载思考内容...",

    conversationCompacted: "对话已压缩",
    compactionSummaryDescription: "此处之前的对话历史已压缩为以下摘要：",
    noSummary: "（无摘要）",
    fileContext: "文件上下文：{context}",
    readFilesCount: "已读取 {count} 个",
    modifiedFilesCount: "已修改 {count} 个",
    modifiedFiles: "已修改的文件",
    readFiles: "已读取的文件",
    hiddenExtensionMessage: "隐藏的扩展消息",
    noMessage: "（无消息）",
    showExtensionMessage: "显示扩展消息",
    copied: "已复制",
    copy: "复制",
    collapse: "收起",
    expand: "展开",
    hideDetails: "隐藏详情",
    showDetails: "显示详情",
    before: "之前",
    after: "之后",
    noOutput: "（无输出）",
    extension: "扩展",
    assistant: "助手",
    favorites: "收藏",
    favorite: "收藏",
    unfavorite: "取消收藏",

    processStepThinking: "思考",
    processStepFileRead: "读取",
    processStepFileCreate: "创建",
    processStepFileEdit: "编辑",
    processStepFileDelete: "删除",
    processStepSearch: "搜索",
    processStepFind: "查找",
    processStepList: "列出",
    processStepRead: "读取",
    processStepFetch: "抓取",
    processStepDelete: "删除",
    processStepCopy: "复制",
    processStepCommand: "运行",
    processStepTool: "工具",
    processStepTodo: "待办",
    processStepArtifact: "产物",
    processStepCompaction: "压缩",
    processStepError: "错误",
    processWorking: "工作中...",
    processUsed: "使用了 {summary}",
    processToolCount: "{count} 个工具",
    processToolsCount: "{count} 个工具",
    processFailedCount: "（{failed} 个失败）",
    processThoughtCount: "{count} 条思考",
    processThoughtsCount: "{count} 条思考",
    processThoughtDone: "已思考 {duration}s",
    processThoughtDoneNoDuration: "已思考",
    processCustomCount: "{count} 个事件",
    processCustomsCount: "{count} 个事件",
    processCompleted: "处理完成",
    processOutput: "处理输出",
    processTabMode: "标签页模式",
    processTimelineMode: "时间线模式",
    processFailedStep: "失败",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

const listeners = new Set<() => void>();

function normalizeLanguage(value: string | undefined): Language {
  return value === "zh-CN" ? "zh-CN" : "en";
}

function subscribe(callback: () => void): () => void {
  listeners.add(callback);
  return () => listeners.delete(callback);
}

function getSnapshot(): Language {
  if (typeof document === "undefined") return "en";
  return normalizeLanguage(document.documentElement.dataset.language);
}

function getServerSnapshot(): Language {
  return "en";
}

function applyLanguage(language: Language) {
  document.documentElement.dataset.language = language;
  document.documentElement.lang = language;
  try {
    localStorage.setItem("pi-language", language);
  } catch {
    // Ignore storage errors (private mode, quota, etc.).
  }
  listeners.forEach((callback) => callback());
}

export function useLanguage() {
  const language = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);

  const setLanguage = useCallback((next: Language) => {
    applyLanguage(next);
  }, []);

  const t = useCallback((key: TranslationKey) => translations[language][key], [language]);

  return { language, setLanguage, t };
}
